### PR TITLE
SMC-Mallows

### PR DESCRIPTION
**Pull request by wleoncio**
# Summary

This PR merges all the work done on the smc-mallows branch, adding C++-translated features from https://github.com/anjastein/SMC-Mallows into the BayesMallows package.

# What this means for the SMC-Mallows project

The most important API additions are listed in the [SMC-Mallows MVP](https://github.com/ocbe-uio/BayesMallows/milestone/1?closed=1) milestone, which will be closed once this merge is complete. The `smc-mallows` branch may also be removed after the merge.

Merging this PR also marks the end of the translation phase of this project. As far as the [SMC-Mallows project](https://github.com/ocbe-uio/BayesMallows/projects/1) is concerned, the SMC implementation is then feature-complete, and we may start preparing for the release at any moment.

The SMC-Mallows project page lives on, though, as there are issues still being worked on (#80, in particular) and opened issues that may be worked on in the future (#91, #112 and #114 as the time of writing, current info [here](https://github.com/ocbe-uio/BayesMallows/projects/1). These changes should not change the API, though, and are aimed to improve the codebase and possibly gain a bit of performance.

### CODE REVIEW

**Comment by osorensen** [comment]
Great work! I'll need some time to read through the code and familiarize myself with it, so expect it to take a day or two.

**Review by osorensen — COMMENTED** [review]
@wleoncio and @anjastein, I will be making some small commits as I work through the SMC-Mallows branch. I'll tag you in each of them, so you know what I'm doing. Here is the first one. If you have any comments or suggestions, please write them here.

**Review by wleoncio — COMMENTED** [review]
A distinction I always try to make, as well. :)

**Comment by wleoncio** [comment]
> Great work! I'll need some time to read through the code and familiarize myself with it, so expect it to take a day or two.

No problem, take your time. I have a couple of fires to put out elsewhere this week, but there should be some free time every now and then (like now), so I'll be around.

**Comment by osorensen** [comment]
[Here](https://github.com/ocbe-uio/BayesMallows/pull/157/commits/0d25e527e0ec30b85d8f23f4f8459dee8ad47ff4) is another one. I moved all the references to `inst/REFERENCES.bib`, to avoid duplication of data. This way we make sure all references are consistent across the package.

**Comment by osorensen** [comment]
@anjastein, I did some editorial changes in the vignette, as you can see [here](https://github.com/ocbe-uio/BayesMallows/pull/157/commits/b36d362ce3a6184d041d6605b7171bb4c084296d) and [here](https://github.com/ocbe-uio/BayesMallows/pull/157/commits/37e8eb26e68c7de82987d98d0b5f9a438742706e). 

Some comments:
- Using  `(@key)` for citations gives two sets of parentheses, e.g., "(Vitelli et al. (2018))". Putting square brackets around `[@key]` improves this somewhat, to "(Vitelli et al. 2018)", so I did this where appropriate. Ideally we should have "(Vitelli et al., 2018)", with a comma, but it does not seem straightforward.
- I did some small typo corrections, but you're the native speaker, so I may well be wrong :-)

**Comment by osorensen** [comment]
[This commit](https://github.com/ocbe-uio/BayesMallows/pull/157/commits/ee3fa459c4b9a7fe35583a3170f20ad8cdb2e8ff) is not directly related to SMC Mallows, but we initially used `test_*` in the test filenames. However, `usethis::test()` creates the prefix `test-*`, and hence we have got a lot of file with that prefix as well. I thus renamed all to start with `test-` so it is easier to search for test files.

**Review by wleoncio — COMMENTED** [review]
Oops, you just reminded me I was going to run `styler::style_file("vignettes/SMC-Mallows.Rmd")` before opening this PR. Maybe I leave this one to you, @osorensen, since you've got your hands on the file? It could help with restyling the spacing around operators and code width.

**Comment by osorensen** [comment]
> Oops, you just reminded me I was going to run `styler::style_file("vignettes/SMC-Mallows.Rmd")` before opening this PR. Maybe I leave this one to you, @osorensen, since you've got your hands on the file? It could help with restyling the spacing around operators and code width.

Yes, I'll fix it.

**Comment by osorensen** [comment]
🎊.🎉

**Comment by anjastein** [comment]
That was incredibly quick work!

**Pull request merged**
