### PR TITLE
created a single setdiff function

### PR DESCRIPTION
**Pull request by osorensen**

### CODE REVIEW

**Comment by osorensen** [comment]
Here is a summary:

I have now got rid of the three different setdiff functions we had previously, by defining a single templated function:

https://github.com/ocbe-uio/BayesMallows/blob/e287a600660eddebf8e93c93ec2d851f7507a2ac/src/setdiff.hpp#L1-L19

I named it `setdiff_template`, but that was mainly to differentiate it from the previous versions we had.

One of the consequences is that the following chunk of code in previous versions

https://github.com/ocbe-uio/BayesMallows/blob/68707cd151a4d900ec35126559feb9c1257321e5/src/smc_mallows_new_item_rank_alpha_fixed.cpp#L95-L105

now is replaced with the following

https://github.com/ocbe-uio/BayesMallows/blob/e287a600660eddebf8e93c93ec2d851f7507a2ac/src/smc_mallows_new_item_rank_alpha_fixed.cpp#L97-L101

There is a caveat which we have to fix later, however. Using `shuffle` instead of `Rcpp::sample` changes the sequences that we get for a given seed, causing the tests to fail. I have therefore many places retained code like this:

https://github.com/ocbe-uio/BayesMallows/blob/e287a600660eddebf8e93c93ec2d851f7507a2ac/src/smc_mallows_new_users_partial_alpha_fixed.cpp#L107-L114

As can be see from the comment on line 112, the long ugly expression on lines 113-114 can be replaced with `partial_ranking.elem(find_nonfinite(partial_ranking)) = shuffle(missing_ranks);`. However, this would require changing some of the expectations for the unit tests, and that is a thing we should go very carefully through later.

**Comment by osorensen** [comment]
I see the checks failed because I used the `.hpp` extension. Will update.

**Review by wleoncio — APPROVED** [review]
This is great, and solves a longstanding issue of using Rcpp objects because I didn't manage to convert them to arma on some specific points. If `arma::shuffle()` is basically the same as `Rcpp::sample()`, do we really need to be that careful with updating the unit tests, though (famous last words)?

**Comment by osorensen** [comment]
> This is great, and solves a longstanding issue of using Rcpp objects because I didn't manage to convert them to arma on some specific points. If `arma::shuffle()` is basically the same as `Rcpp::sample()`, do we really need to be that careful with updating the unit tests, though (famous last words)?

I agree. But we need to be aware that using a different function leads to different permutations for the same random number seed, even though the overall distributions will be the same. So we should confirm that the results in the SMC vignette and examples look the same, even though the last decimals in the numbers might be slightly different. Makes sense?

**Comment by wleoncio** [comment]
Makes sense, no reason not to take it steady! :)

**Comment by osorensen** [comment]
Then I'll update shuffle and tests in another PR :-)

**Pull request merged**
