### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by osorensen**

### CODE REVIEW

**Comment by osorensen** [comment]
An attempt at solving #312. Along the way I discovered that many functions that are not directly aimed at users were exported. I added `#' keywords internal` to avoid that they end up in the index. Could alternatively have added `#' @noRd`, which would make these functions completely internal.

**Review by wleoncio — CHANGES_REQUESTED** [review]
I'm afraid `@keywords internal` breaks the package, I got the same results on my local build. :-/

Trying a couple of things myself over here. So far, nothing.

**Comment by osorensen** [comment]
Oh yes sorry, I should have checked this myself. Some of the examples use some functions that I internalized, so those should be exported.

**Comment by osorensen** [comment]
I think I know what to do. One moment.

**Comment by osorensen** [comment]
Coverting this to a draft, as I discovered a number of issues while I started digging. Will have to work on it.

- [ ] [The SMC Mallows vignette](https://ocbe-uio.github.io/BayesMallows/articles/SMC-Mallows.html) uses compute_posterior_intervals_alpha() and compute_posterior_intervals_rho() directly, but this should be done by calling compute_posterior_intervals() with argument `parameter = "alpha"` or `parameter = "rho"`.
- [ ] [The SMC Mallows vignette](https://ocbe-uio.github.io/BayesMallows/articles/SMC-Mallows.html) uses the function compute_consensus_rho(), but we also have an S3 method [compute_consensus()](https://ocbe-uio.github.io/BayesMallows/reference/compute_consensus.consensus_SMCMallows.html) which I think should be called instead. From what I can tell, the function compute_rho_consensus() could be deleted.
- [ ] Most of the functions I marked internal should perhaps not be exported at all.

I have time to look at this today, so will test a couple of things, and get back.

**Comment by osorensen** [comment]
Some notes:

S3 method compute_posterior_intervals() is not called directly for SMC Mallows objects. Instead it is called internally by compute_posterior_intervals_alpha() and compute_posterior_intervals_rho(). For consistency with the other parts of the package, I think we should do otherwise, but then we get a bigger job.

**Comment by wleoncio** [comment]
> Some notes:
> 
> S3 method compute_posterior_intervals() is not called directly for SMC Mallows objects. Instead it is called internally by compute_posterior_intervals_alpha() and compute_posterior_intervals_rho(). For consistency with the other parts of the package, I think we should do otherwise, but then we get a bigger job.

You had me at "consistency", but unless it's trivial to resolve, I think it should be worked separately as a different issue. I'll create one for that and we'll close it if it gets resolved indirectly.

**Comment by osorensen** [comment]
@wleoncio, this PR now becomes pretty massive, but it should fix #318 as well as a couple of other consistency issues I stumbled upon. 

Please take your time and, feel welcome to ask critical questions when reviewing it :-)

**Review by wleoncio — APPROVED** [review]
Great job, codebase looks much cleaner, now!

**Comment by wleoncio** [comment]
BTW, what do you think about making `develop` the default branch in the settings? This allows for to auto-closing of linked issues when PRs merge into develop (instead of just when they merge into master) or when commit messages contain some [keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests); also, PRs will also default to merging into the develop branch, which is the case more often than not. Master is basically just tracking CRAN anyway. :)

**Comment by osorensen** [comment]
> BTW, what do you think about making `develop` the default branch in the settings? This allows for to auto-closing of linked issues when PRs merge into develop (instead of just when they merge into master) or when commit messages contain some [keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests); also, PRs will also default to merging into the develop branch, which is the case more often than not. Master is basically just tracking CRAN anyway. :)

Actually I'm kind of thinking that master should contain the latest development version. This seems to be the default, e.g., for tidyverse packages like [dplyr](https://github.com/tidyverse/dplyr/), so I would kind of prefer to update the master branch more often, so that people can actually install the development version using `remotes::install_github("ocbe-uio/BayesMallows")`.

**Comment by wleoncio** [comment]
> Actually I'm kind of thinking that master should contain the latest development version. This seems to be the default, e.g., for tidyverse packages like [dplyr](https://github.com/tidyverse/dplyr/), so I would kind of prefer to update the master branch more often, so that people can actually install the development version using `remotes::install_github("ocbe-uio/BayesMallows")`.

That works too! I've considered doing that myself, as it sometimes feel redundant to have a branch just to track the CRAN releases, but I always end up keeping it because it (arguably) makes releases easier to see in the Git tree than if releases were just tags.

**Comment by wleoncio** [comment]
Oh, and before we forget: if we use `master` as the development branch we'll need to edit `pkddown.yaml` to trigger a page update on something else, like the releases page, otherwise we'll have a GH page for each dev version. 😬

**Pull request merged**
