### PR TITLE
Smc issue 306

### PR DESCRIPTION
**Pull request by osorensen**
First step towards #306

### CODE REVIEW

**Comment by osorensen** [comment]
@wleoncio, I'm not sure we're ready to merge yet, but I'd really like some feedback and criticism, hence requesting you to review :-)

**Comment by osorensen** [comment]
Thanks @crispinomarta! I wasn't aware of this, but this is definitely something to add. I'll open a new issue for it. Might as always take some time before I get around to actually doing it, but should definitely add it at some point.

**Comment by osorensen** [comment]
Converting to draft. Seems to be a bug in the updated function for new users. I'll do some more development on my side, including making more tests to make sure it reproduces the result of using existing functions.

**Comment by osorensen** [comment]
Note to future self: I created a very long-running test to confirm the correctness of `smc_mallows_update.SMCMallowsNewUsers()`. Need to do the same for `smc_mallows_update.SMCMallowsUpdatedPartial()` before converting back from draft.

**Comment by wleoncio** [comment]
> @wleoncio, I'm not sure we're ready to merge yet, but I'd really like some feedback and criticism, hence requesting you to review :-)

Happy to contribute, I'll just wait for it to be marked again as "ready for review".

Regarding the long tests, you may want to consider using testthat's [skip functions](https://testthat.r-lib.org/reference/skip.html) so they're not _always_ run.

**Comment by osorensen** [comment]
Thanks @wleoncio, I'll ping you.

> Regarding the long tests, you may want to consider using testthat's [skip functions](https://testthat.r-lib.org/reference/skip.html) so they're not always run.

I am :-)

https://github.com/ocbe-uio/BayesMallows/blob/86c714aeb67d132eaf256a905cd43956fa12eeae/.github/workflows/R-CMD-check.yaml#L27-L30

https://github.com/ocbe-uio/BayesMallows/blob/86c714aeb67d132eaf256a905cd43956fa12eeae/tests/testthat/test-smc-update-correctness.R#L10-L69

**Pull request closed without merging**
