### PR TITLE
Update smc_mallows_new_users_partial.cpp

### PR DESCRIPTION
**Pull request by anjastein**
Include a vector named `ESS_vec` (a vector of length Time) which contains the Effective Sample Size of the particles in each iteration.
Return the `aug_rankings` at end of SMC algorithm.

### CODE REVIEW

**Review by wleoncio — CHANGES_REQUESTED** [review]
Please see my comments on https://github.com/ocbe-uio/BayesMallows/pull/189#pullrequestreview-937537853.

**Comment by wleoncio** [comment]
@anjastein, I think you can just replicate the changes from PR #189 (see diff [here](https://github.com/ocbe-uio/BayesMallows/pull/189/files)) here.

**Review by wleoncio — APPROVED** [review]
All good, just waiting for @osorensen's approval so we can merge.

**Review by osorensen — APPROVED** [review]

**Review by osorensen — CHANGES_REQUESTED** [review]
The documentation does not really match the return values.

**Review by osorensen — CHANGES_REQUESTED** [review]
The documentation says: 

https://github.com/anjastein/BayesMallows/blob/3e296d5d797d635dc3844b66a52e7941f22e3ee8/src/smc_mallows_new_users_partial.cpp#L34

But the return value is

https://github.com/anjastein/BayesMallows/blob/3e296d5d797d635dc3844b66a52e7941f22e3ee8/src/smc_mallows_new_users_partial.cpp#L237-L242

Please update the documented return value.

**Comment by wleoncio** [comment]
> Please update the documented return value.

Good point, and good looking out, Øystein! I'll change my review accordingly 😄

**Review by wleoncio — CHANGES_REQUESTED** [review]
@anjastein, please edit L34 to reflect the proposed output.

**Review by osorensen — APPROVED** [review]

**Pull request merged**
