### PR TITLE
Fixed Cpp issue

### PR DESCRIPTION
**Pull request by osorensen**

### CODE REVIEW

**Comment by wleoncio** [comment]
Damn, we should have coordinated a bit. I was working on the same thing, but did the opposite (changed the other `n_*` variables to unsigned). 😆

**Comment by osorensen** [comment]
> IIRC, I'm afraid using int as indices for arma objects also causes warnings (not check failures, though).

Are you sure? I don't think I've ever used `uword` or similar for arma objects, and haven't got any warnings. I also went in and looked at some of the checks for this PR, and could not find any warnings about it.

**Comment by osorensen** [comment]
Interesting to get to the bottom of this. Could not find any notes or warnings in my own build log, but trying out `rhub` with santizers now.,

**Comment by wleoncio** [comment]
> > IIRC, I'm afraid using int as indices for arma objects also causes warnings (not check failures, though).
> 
> Are you sure? I don't think I've ever used `uword` or similar for arma objects, and haven't got any warnings. I also went in and looked at some of the checks for this PR, and could not find any warnings about it.

Couldn't confirm it on a local (Linux) compilation, so it's either not a problem anymore or just my memory tricking me. In my defense, the [Arma docs](https://arma.sourceforge.net/docs.html) state that "when using loops to access elements, it is best to use uword instead of int".

In any case, the most important thing is that all elements in the loops have the same signedness. :)

**Review by wleoncio — APPROVED** [review]

**Comment by osorensen** [comment]
Then let's keep it this way until a warning pops up. rhub seems happy to. 

I do see the point that trying to access a vector element with a negative integer will lead to failure, however, it gives a nice error message, and thus presumably does not qualify as undefined behavior(?)

Tryed it with this program:

```cpp
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

// [[Rcpp::export]]
int test(arma::mat X, int i) {
  Rcpp::Rcout << X.col(i) << std::endl;
  
  return 0;
}
```

And it gave this output:

```r
> test(matrix(rnorm(6), nrow = 3), 1L)
   0.2643
   1.7759
   1.9572

[1] 0
> test(matrix(rnorm(6), nrow = 3), -1L)
Error: Mat::col(): index out of bounds
```

**Pull request merged**
