### PR TITLE
Reduced tests which took long time

### PR DESCRIPTION
**Pull request by osorensen**
Kept all the same tests but reduced the number of iterations in those that took a long time to run. This will enable us to add more tests later without getting timing issues. It's particularly important on valgrind, where tests take really long to run, so we bump into the 20-minute limit.

Here is before (i.e., master branch):

```r
> devtools::test()
i Loading BayesMallows
i Testing BayesMallows
√ |  OK F W S | Context
√ |   5       | Testing assess_convergence [0.2 s]                                                       
√ |  18       | Testing compute_consensus [6.4 s]                                                        
√ |  36       | Testing compute_mallows [7.3 s]                                                          
√ |  26       | Testing computation of distance                                                          
√ |   6       | Testing function estimate_partition_function                                             
√ |   9       | expected_dist                                                                            
√ |  12       | Testing generation of initial ranking [0.7 s]                                            
√ |   5       | lik_db_mix                                                                               
√ |   4       | Testing MCMC function on potato data [0.1 s]                                             
√ |   6       | Testing misc C++ functions                                                               
√ |   4       | Testing misc functions                                                                   
√ |  58       | Testing computation of partition functions [0.1 s]                                       
√ |   4       | Testing plot.BayesMallows                                                                
√ |   4       | Testing plot_elbow [0.2 s]                                                               
√ |  15       | Testing plot_top_k and predict_top_k [3.4 s]                                             
√ |   5       | Testing print.BayesMallows and print.BayesMallowsMixtures                                
√ |   2       | Testing that the random numbers are equal between platforms [1.1 s]                      
√ |   6       | Testing rank_conversion                                                                  
√ |   4       | rank_freq_distr                                                                          
√ |  16       | Testing sample_mallows [0.8 s]                                                           
√ |   2       | Testing functions for pairwise preferences                                               

== Results ==============================================================================================
Duration: 21.0 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 247 ]
```

Here is after (i.e., this pull request):

```r
> devtools::test()
i Loading BayesMallows
i Testing BayesMallows
√ |  OK F W S | Context
√ |   5       | Testing assess_convergence [0.2 s]                                                       
√ |  18       | Testing compute_consensus [3.1 s]                                                        
√ |  36       | Testing compute_mallows [1.2 s]                                                          
√ |  26       | Testing computation of distance                                                          
√ |   6       | Testing function estimate_partition_function                                             
√ |   9       | expected_dist                                                                            
√ |  12       | Testing generation of initial ranking [0.7 s]                                            
√ |   5       | lik_db_mix                                                                               
√ |   4       | Testing MCMC function on potato data [0.1 s]                                             
√ |   6       | Testing misc C++ functions                                                               
√ |   4       | Testing misc functions                                                                   
√ |  58       | Testing computation of partition functions [0.1 s]                                       
√ |   4       | Testing plot.BayesMallows                                                                
√ |   4       | Testing plot_elbow [0.2 s]                                                               
√ |  15       | Testing plot_top_k and predict_top_k [2.8 s]                                             
√ |   5       | Testing print.BayesMallows and print.BayesMallowsMixtures                                
√ |   2       | Testing that the random numbers are equal between platforms [1.0 s]                      
√ |   6       | Testing rank_conversion                                                                  
√ |   4       | rank_freq_distr                                                                          
√ |  16       | Testing sample_mallows [0.8 s]                                                           
√ |   2       | Testing functions for pairwise preferences                                               

== Results ==============================================================================================
Duration: 10.8 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 247 ]
```

### CODE REVIEW

**Comment by osorensen** [comment]
This is related to issue #103 .

**Comment by wleoncio** [comment]
> This is related to issue #103 .

#102, you mean? 😝

**Review by wleoncio — APPROVED** [review]
Good job, a 2x speed increase is definitely welcome.

**Comment by wleoncio** [comment]
CI test is not expected to run (see #101), so I'll merge immediately.

**Comment by osorensen** [comment]
Haha, yes :D #102 I mean

**Pull request merged**
