### PR TITLE
Added CodeFactor badge

### PR DESCRIPTION
**Pull request by wleoncio**
Small change I made while waiting for checks to complete. This supplements the linter checks we already have and makes it easier to see code that could be rewritten and measure refactoring improvements. As the package grows, these small things become more and more important.

### CODE REVIEW

**Comment by osorensen** [comment]
Awesome!

**Review by osorensen — APPROVED** [review]

**Comment by wleoncio** [comment]
Hang on, I made the changes on the md instead the Rmd...

**Comment by wleoncio** [comment]
@osorensen, please check if the other changes triggered by `devtools::build_readme()` actually reflect the most recent state of the document, particularly the references (I suspect they don't). I took a look at the README.md history and it seems like the latest version of the text should be the one on c8fb9bcf112a256e9d9e0e45671d0e164118d6b5.

**Review by osorensen — APPROVED** [review]
Nice!

**Comment by osorensen** [comment]
> @osorensen, please check if the other changes triggered by `devtools::build_readme()` actually reflect the most recent state of the document, particularly the references (I suspect they don't). I took a look at the README.md history and it seems like the latest version of the text should be the one on [c8fb9bc](https://github.com/ocbe-uio/BayesMallows/commit/c8fb9bcf112a256e9d9e0e45671d0e164118d6b5).

I think we have to manually compile `README.Rmd`, right? It's possible to set up GitHub Actions to do this, but I don't think we have. I'll look at the changes and check.

**Comment by osorensen** [comment]
Not sure I completely understood the issue, but [my latest commit](https://github.com/ocbe-uio/BayesMallows/pull/213/commits/db62ddfca257e1e840ff534cb82e5aeae496aa61) shows that `README.md` changed after I compiled `README.Rmd` locally.

**Comment by wleoncio** [comment]
I'm a bit confused myself. What command does that button run? `devtools::build_readme()` eventually just runs `rmarkdown::render(...), args = list(input = path, ..., output_options = output_options, quiet = quiet), show = TRUE, spinner = FALSE, stderr = "2>&1")`, and if I run it on db62ddfca257e1e840ff534cb82e5aeae496aa61 I get back to 4e3281643b414d738e595a2eaeaf0ed1cca9e061. 😕

**Comment by osorensen** [comment]
Not on my side. Running `devtools::build_readme()` generates new versions of the `.png` plots, but does not change `README.md`, so it seems to be identical to the button.

**Comment by wleoncio** [comment]
OK, in that case it seems safe to merge with your version; I'll figure out what's happening on my end later.

**Pull request merged**
