### PR TITLE
Weights

### PR DESCRIPTION
**Pull request by osorensen**
I have now implemented a `weights` argument which utilizes repeated patterns in the rank or preference data, cf. Issue #43 . 

Here is a little test which shows the potential for speedup:
  
  ``` r
library(BayesMallows)
library(purrr)
# The first example uses full rankings in the potato_visual dataset, but we assume
# that each row in the data corresponds to between 100 and 500 assessors.
set.seed(1234)
# We start by generating random sample weights
weights <- sample(x = seq(from = 100L, to = 500L, by = 1L),
                  size = nrow(potato_visual), replace = TRUE)
# We also create a set of repeated indices, used to extend the matrix rows
repeated_indices <- unlist(map2(1:nrow(potato_visual), weights, ~ rep(.x, each = .y)))
# The potato_repeated matrix consists of all rows repeated corresponding to
# the number of assessors in the weights vector. This is how a large dataset
# would look like without using the weights argument
potato_repeated <- potato_visual[repeated_indices, ]

# We now first compute the Mallows model using weights
# This takes about 0.2 seconds
system.time({
  m_weights <- compute_mallows(rankings = potato_visual, weights = weights, nmc = 10000)
})
#>    user  system elapsed 
#>   0.408   0.022   0.430
# Next we use the full ranking matrix
# This takes about 11.3 seconds, about 50 times longer!
system.time({
  m_rep <- compute_mallows(rankings = potato_repeated, nmc = 10000)
})
#>    user  system elapsed 
#>  11.221   0.026  11.251
```

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
  
  The `weights` argument is documented in `help("compute_mallows")`, but I have also created a separate example page which can be assessed with `help("sample_weights")`, but is also linked to from the `compute_mallows` documentation. I have also added unit tests in `tests/testthat/test_compute_mallows.R`. We definitely need some more thorough testing of these weights, but this is at least a start.

This might be relevant for you, @cmollica.

### CODE REVIEW

**Review by wleoncio — COMMENTED** [review]
Sorry for the late reply, I was out on vacation; Took a quick look just for the record, since it's already been merged. Code looks good anyway.

**Comment by MartaCrispino** [comment]
Hi all, I am not able to use the argument obs_freq with pairwise preferences. Is it still to be implemented or I am wrong in my code?

**Comment by osorensen** [comment]
Thanks for feedback, @MartaCrispino. It works in the example given on the help page `help("obs_freq")`. See the bottom examples. But you have to generate the transitive closure and initial rankings yourself. Could you take a look at those examples, and if it still does not work, please create a new Issue, and paste a simple reproducible example showing how it fails?

**Comment by MartaCrispino** [comment]
Thanks @osorensen. Now it works perfectly. Marta

**Pull request merged**
