### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by osorensen**
Small adjustments before submitting update to CRAN.

### CODE REVIEW

**Review by wleoncio — APPROVED** [review]
So happy to see this happening! :)

**Comment by wleoncio** [comment]
Shouldn't we keep `develop` alive to receive commits for the next release?

**Comment by osorensen** [comment]
Agreed, but I had to work through a bunch of conflicts when merging with the master branch, so my quick and dirty solution was to delete the `develop` branch and open a new one from the new master branch.

**Comment by wleoncio** [comment]
Fair enough. I've got some conflicts merging `ocbe-uio/master` into my local copy of `develop`, but using `git merge master --strategy-option=theirs` worked fine. ;)

**Comment by osorensen** [comment]
Thanks, I really enjoy learning GitHub stuff from you :-)

**Pull request merged**
