### PR TITLE
A lot of changes

### PR DESCRIPTION
**Pull request by osorensen**

### CODE REVIEW

**Comment by osorensen** [comment]
The Linter error is a false positive. It reports on the `library()` statements in this example, but since `ggplot2` is listed in `Imports` I think it is absolutely fine. `R CMD check` does not report on it either.

https://github.com/ocbe-uio/BayesMallows/blob/35dd003922ac96a19dc340c1f4cbe84f19ba76a8/inst/examples/compute_mallows_sequentially_example.R#L1-L5

**Comment by osorensen** [comment]
Should close #394 and #386

**Comment by wleoncio** [comment]
> The Linter error is a false positive. It reports on the `library()` statements in this example, but since `ggplot2` is listed in `Imports` I think it is absolutely fine. `R CMD check` does not report on it either.
> 
> https://github.com/ocbe-uio/BayesMallows/blob/35dd003922ac96a19dc340c1f4cbe84f19ba76a8/inst/examples/compute_mallows_sequentially_example.R#L1-L5

Alright, but then perhaps we should add those lines to [linter.yml](https://github.com/ocbe-uio/BayesMallows/blob/8850531c2bb231bd032b5909d8e64cdd00c9d654/.github/workflows/linter.yml#L43-L65) so CI doesn't bothers us about it.

**Review by wleoncio — APPROVED** [review]
Good job, interesting solution with the `burnin()` function!

**Comment by osorensen** [comment]
> > The Linter error is a false positive. It reports on the `library()` statements in this example, but since `ggplot2` is listed in `Imports` I think it is absolutely fine. `R CMD check` does not report on it either.
> > https://github.com/ocbe-uio/BayesMallows/blob/35dd003922ac96a19dc340c1f4cbe84f19ba76a8/inst/examples/compute_mallows_sequentially_example.R#L1-L5
> 
> Alright, but then perhaps we should add those lines to [linter.yml](https://github.com/ocbe-uio/BayesMallows/blob/8850531c2bb231bd032b5909d8e64cdd00c9d654/.github/workflows/linter.yml#L43-L65) so CI doesn't bothers us about it.

Absolutely. I'll add that now.

**Comment by osorensen** [comment]
@wleoncio I think I managed to fix the linter issue, but do you know where CodeFactor gets its settings from?

**Comment by wleoncio** [comment]
> @wleoncio I think I managed to fix the linter issue, but do you know where CodeFactor gets its settings from?

Unfortunately, that's still a mystery to me 😅

**Pull request merged**
