### PR TITLE
Declared constants and references (#112)

### PR DESCRIPTION
**Pull request by wleoncio**
Some minor changes to finish up my work day. This takes care of another 2/4 of the tasks on issue #112, leaving just one last checkbox to close the issue.

Summary of changes:

- Declared constants and references on SMC (#112)
- Removed trailing blank line (the CI linter was complaining)

### CODE REVIEW

**Comment by osorensen** [comment]
Nice work @wleoncio!

I have a question:

Are you sure what you have done here leads to improved memory management? 

Consider for example these lines

https://github.com/ocbe-uio/BayesMallows/blob/63d8c4e7c357c213e8919af27a8ad8399a906e67/src/smc_calculate_forward_probability.cpp#L35-L38

Isn't the `const` qualifier just a way of ensuring that the values won't be changed? Will they not still be copied? 

Based on my memories of C++, you would have to add the ampersand `&` to make these values call-by-references, such that the function does not create a copy, but instead accesses them directly from the location in memory. In this case, the `const` is very important, because without it, the function could go ahead and modify the values of the arguments provided to it by the caller.

I would hence guess that it should be

```
  
const arma::vec& rho,
const double& alpha,
const int& n_items,
const std::string& metric
```

and similar elsewhere.

Sorry that I don't have time to read up on this right now, and I'm happy to be proven wrong :)

**Comment by wleoncio** [comment]
Hi Øystein,

> Isn't the `const` qualifier just a way of ensuring that the values won't be changed? Will they not still be copied?

I think you're right. I just blindly assume that using `const` and `&` lessen the load on computer resources (or don't increase them), so I'm glad you've challenged this. It'd be lovely if @grosed could chime in. 😃 

In any case, as far as using `&` on function arguments, I've been avoiding those because I don't quite understand how they work. On the function body, they seem pretty straightforward―as a reference, so that `int& y = x` indicates that y is an alias for x`―, but on a function header it just goes over my head about what it does (I may need to spend some time with a low-level language to get over some trauma about memory-allocation 😆).

In any case, putting ampersand on the variables you suggested doesn't work here, even if I try them individually I get this error when trying to build the package:

> Error in dyn.load(dll_copy_file) : 
>  unable to load shared object '/tmp/RtmpPSOwqr/pkgload72dc63dc16c4/BayesMallows.so':
>  /tmp/RtmpPSOwqr/pkgload72dc63dc16c4/BayesMallows.so: undefined symbol: >_Z29calculate_forward_probabilityN4arma3ColIjEENS0_IdEES2_S2_diNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

The only thing I could think of to deal with this "undefined symbol" error is to change the file encoding, but that only makes things worse.

**Comment by wleoncio** [comment]
> Are you sure what you have done here leads to improved memory management?

Another thing I was wondering: what's a good way to benchmark this? I thought about doing `rhub::check(..., valgrind = TRUE)` on both branches and comparing the results, but that sounds like a roundabout way of doing this.

**Comment by grosed** [comment]
Sorry - forgot the attachment !! 
    
   
   
    
   
  
    Dan 
    
   
   
   
     On 07/02/2022 15:24 Daniel Grose ***@***.***> wrote: 
    
    
     
    
    
     
    
   
     Hi 
     
    
    
     
    
   
     Good to hear from you. Hope you are both keeping well. 
     
    
    
     
    
   
     I have made a few notes about how c++ passes objects to functions (attached). Hope this helps you understand what is going on. 
     
    
    
     
    
   
     Regarding the package - your error is to do with linkage, not compilation. The linker cannot find a symbol, which means it doesn't know where to look, or it was never compiled to an object in the first place. I have not got time at the moment to check this out - I will have a look at it tomorrow and get back to you. 
     
    
    
     
    
   
     Best wishes, 
     
    
   
     Dan 
     
    
    
    
      On 07/02/2022 08:00 Waldir Leoncio ***@***.***> wrote: 
     
     
      
     
     
      
     
     
    Hi Øystein, 
     
     Isn't the const qualifier just a way of ensuring that the values won't be changed? Will they not still be copied? 
     
    I think you're right. I just blindly assume that using const and & lessen the load on computer resources (or don't increase them), so I'm glad you've challenged this. It'd be lovely if @grosed could chime in. 😃 
    In any case, as far as using & on function arguments, I've been avoiding those because I don't quite understand how they work. On the function body, they seem pretty straightforward―as a reference, so that int& y = x indicates that y is an alias for x`―, but on a function header it just goes over my head about what it does (I may need to spend some time with a low-level language to get over some trauma about memory-allocation 😆). 
    In any case, putting ampersand on the variables you suggested doesn't work here, even if I try them individually I get this error when trying to build the package: 
     
     Error in dyn.load(dll_copy_file) :unable to load shared object '/tmp/RtmpPSOwqr/pkgload72dc63dc16c4/BayesMallows.so':/tmp/RtmpPSOwqr/pkgload72dc63dc16c4/BayesMallows.so: undefined symbol: >_Z29calculate_forward_probabilityN4arma3ColIjEENS0_IdEES2_S2_diNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 
     
    The only thing I could think of to deal with this "undefined symbol" error is to change the file encoding, but that only makes things worse.

**Comment by osorensen** [comment]
@wleoncio, here is how I did this for the other C++ code in the package, using the function for initializing missing values as an example:

https://github.com/ocbe-uio/BayesMallows/blob/ef3d9c2342d371e4367044e27463f95a244cedaa/src/missing_data.cpp#L14-L38

My interpretation is as follows:
`void` means that the function does not return anything. `arma::mat& rankings` means that the `rankings` object is not copied into the function, but instead the function just gets a reference to it. `const arma::umat& missing_indicator` and `const arma::uvec& assessor_missing` also means that the function gets references to these object, but that it is not allowed to modify them. These latter two objects are hence completely "safe". The loop then updates the `rankings` object by directly modifying positions in memory of the `rankings` object used when calling the function.

Here is how the function is called. Note that there is no return value.

https://github.com/ocbe-uio/BayesMallows/blob/ef3d9c2342d371e4367044e27463f95a244cedaa/src/run_mcmc.cpp#L103

I did some small tests which indicated that things got faster, but I have not done extensive testing. It also occurs to me that this might be bad practice since the code becomes very unreadable.

@wleoncio, my suggestion is that we merge this PR, but keep in mind for later that it can be interesting to understand better how these issues affect performance. Agree?

**Comment by wleoncio** [comment]
> this way of writing code might be bad practice since the code becomes very unreadable.

Got a bit lost here, do you mean using `const`? And since we're on this topic of readability, I've always wondered if you've considered adding Rcpp and/or RcppArmadillo as namespaces on the Cpp files so we could drop all instances of `arma::` and/or `Rcpp::` (wherever there are no name conflicts, that is).

I haven't done extensive reading on best C++ coding practices, but I did find a [vaguely-related thread](https://softwareengineering.stackexchange.com/q/50120) that made me think we should have one "main" userspace (perhaps RcppArmadillo,which is the most used in our project).

> @wleoncio, my suggestion is that we merge this PR, but keep in mind for later that it can be interesting to understand better how these issues affect performance. Agree?

Agreed, and thanks for the insight!

**Comment by osorensen** [comment]
> Got a bit lost here, do you mean using const? And since we're on this topic of readability, I've always wondered if you've considered adding Rcpp and/or RcppArmadillo as namespaces on the Cpp files so we could drop all instances of arma:: and/or Rcpp:: (wherever there are no name conflicts, that is).

I was more thinking of the fact that the void functions don't have a return value, so it's hard to understand which arguments they're actually modifying.

And yes, I think I had `using namespace ...` directives in the beginning, but then ran into issues where the armadillo log function returned different things than the `std::log` function, which caused subtle bugs, so for the sake of safety, I felt that it was better to be explicit.

**Pull request merged**
