### PR TITLE
Issue 200

### PR DESCRIPTION
**Pull request by osorensen**
Working towards #200.

### CODE REVIEW

**Comment by osorensen** [comment]
This PR builds upon #203.

**Review by wleoncio — APPROVED** [review]
Always nice to see cleaner code. Hope we don't regret this. 😆

**Comment by osorensen** [comment]
> Always nice to see cleaner code. Hope we don't regret this. 😆

Hope so :-)

Btw, I merged the latest PR first, and created some conflicts. I should probably do it in the opposite order..

**Comment by wleoncio** [comment]
> Btw, I merged the latest PR first, and created some conflicts. I should probably do it in the opposite order..

Alright, give me a minute, I'm almost done with #199.

**Comment by osorensen** [comment]
> > Btw, I merged the latest PR first, and created some conflicts. I should probably do it in the opposite order..
> 
> Alright, give me a minute, I'm almost done with #199.

Thanks, and no problem :-)

**Comment by osorensen** [comment]
Don't worry about the conflicts @wleoncio, I think I fixed them, but will let all the tests run once more before merging.

**Pull request merged**
