### PR TITLE
Update smc_mallows_new_users_partial_alpha_fixed.cpp

### PR DESCRIPTION
**Pull request by anjastein**
Include a vector named `ESS_vec` (a vector of length Time) which contains the Effective Sample Size of the particles in each iteration.
Return the `aug_rankings` at end of SMC algorithm.

### CODE REVIEW

**Comment by wleoncio** [comment]
@anjastein, I think you can just replicate the changes from PR #189 (see diff [here](https://github.com/ocbe-uio/BayesMallows/pull/189/files)) here.

**Review by wleoncio — APPROVED** [review]
All good, just waiting for @osorensen's approval so we can merge.

**Review by wleoncio — CHANGES_REQUESTED** [review]
@anjastein, please edit L28 to reflect the proposed output.

**Review by osorensen — CHANGES_REQUESTED** [review]
As @wleoncio pointed out, please update documentation.

**Review by osorensen — APPROVED** [review]

**Review by wleoncio — APPROVED** [review]

**Pull request merged**
