### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by osorensen**

### CODE REVIEW

**Comment by osorensen** [comment]
Comment: I'll wait for @anjastein's updates in #249 before submitting to CRAN, so converting this one to a draft for now.

**Comment by osorensen** [comment]
Since there has been some changes in C++ code with [this commit](https://github.com/ocbe-uio/BayesMallows/pull/251), I'll rerun the rhub CLANG-UBSAN and valgrind tests once more.

**Comment by osorensen** [comment]
image

**Comment by anjastein** [comment]
Great work, Øystein!

**Comment by osorensen** [comment]
image

**Pull request merged**
