### PR TITLE
Update smc_mallows_new_users.cpp

### PR DESCRIPTION
**Pull request by anjastein**
- added loop for `partial` and `partial fixed` case to lines 191 and 
- adjusted loop start and endpoints lines 209 and 220

### CODE REVIEW

**Comment by osorensen** [comment]
Thanks @anjastein! The C++ code looks good, but the tests are failing due to your bug fix. I'll update them soon.

**Comment by anjastein** [comment]
Your laptop/monitor set-up is far quicker than my laptop to see these issues!

**Comment by anjastein** [comment]
Just wanted to quickly get confirmation of something in `smc_new_users_funs`. When performing the augmentation with the uniform proposal kernel, `random`. does the function `divide_by_fact` take the current value of aug_prob(ii) and multiply it by 1/factorial(number of missing ranks)? I've attached a snapshot of the function script for reference.
image

**Comment by osorensen** [comment]
Yes, it's a bit subtle, but you can see it here:

https://github.com/ocbe-uio/BayesMallows/blob/8e7ecd316568b0f1e2b568baf106fd7cb22747e0/src/misc.cpp#L48-L52

The `/=` notation means `prob = prob / Gamma(set_length + 1) = prob / factorial(set_length)`.

**Review by osorensen — APPROVED** [review]
Thanks! Great that you discovered this :-)

**Comment by osorensen** [comment]
I changed the function a bit to make it more readable, and short

https://github.com/anjastein/BayesMallows/blob/85ee99f7bf5abc22f5325024f9a6db953051d8bd/src/misc.cpp#L48-L51

**Comment by anjastein** [comment]
That's great!

**Pull request merged**
