### PR TITLE
Removed dependency purrr

### PR DESCRIPTION
**Pull request by osorensen**
This is a step towards #142.

### CODE REVIEW

**Review by wleoncio — APPROVED** [review]
Good job, Øystein! 👏🏽

**Comment by osorensen** [comment]
Thanks @wleoncio. I see there is an issue in the tests, so will fix before merging.

**Comment by wleoncio** [comment]
For the merge, I suggest using "squash and merge", since all the commits are basically fixups of the same thing. 😉 

BTW, really impressed with the [test coverage](https://app.codecov.io/gh/ocbe-uio/BayesMallows) jumping almost 20 p.p.. Way to go!

**Comment by osorensen** [comment]
> For the merge, I suggest using "squash and merge", since all the commits are basically fixups of the same thing. 😉
> 
> BTW, really impressed with the [test coverage](https://app.codecov.io/gh/ocbe-uio/BayesMallows) jumping almost 20 p.p.. Way to go!

Thanks, I'll try Squash and Merge :-)

**Pull request merged**
