### PR TITLE
Pairwise preferences now supported for SMC

### PR DESCRIPTION
**Pull request by osorensen**

### CODE REVIEW

**Comment by osorensen** [comment]
Tests are missing, hence this is still just a draft.

**Comment by osorensen** [comment]
Should solve #398 by removing a test, and solve #395, #388, #385.

**Comment by wleoncio** [comment]
Soooo, is it ready for review now?

**Comment by wleoncio** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/ocbe-uio/bayesmallows) found an issue: Redundant blank line at the start of a code block should be deleted.

It's currently on:
[src\missing_data_functions.cpp:32](https://github.com/ocbe-uio/BayesMallows/blob/fc19e4085472c27295d891ee9a2cc26a922a1457/src/missing_data_functions.cpp#L32)
Commit fc19e4085472c27295d891ee9a2cc26a922a1457

**Pull request merged**
