### PR TITLE
replaced Rcpp::sample with arma::shuffle, #227

### PR DESCRIPTION
**Pull request by osorensen**
I updated the unit tests and also went through the SMC vignette and confirmed that all results are indistinguishable from what they were in the previous version. 

Also used the following script to confirm that `Rcpp::sample(x, x.size())` gives identical distribution to `arma::shuffle(x)`.

```cpp
#include "RcppArmadillo.h"
using namespace arma;

// [[Rcpp::depends(RcppArmadillo)]]

// [[Rcpp::export]]
vec perm_rcpp(vec x) {
  Rcpp::NumericVector x1 = Rcpp::as<Rcpp::NumericVector>(Rcpp::wrap(x));
  Rcpp::NumericVector x2 = Rcpp::sample(x1, x1.size());
  return Rcpp::as<vec>(Rcpp::wrap(x2));
}

// [[Rcpp::export]]
vec perm_arma(vec x){
  return shuffle(x);
}

/*** R
# Confirm that same seed gives different permutation
set.seed(2)
perm_rcpp(1:4)
set.seed(2)
perm_arma(1:4)

# Confirm that overall distribution is identical
set.seed(22)
nmc <- 100000
lapply(c(perm_arma, perm_rcpp), function(fn){
  table(replicate(nmc, paste(perm_arma(1:4), collapse = ""), simplify = "list"))
})

*/

```

### CODE REVIEW

**Comment by osorensen** [comment]
The results of some of the tests seem to be platform dependent. I'll look into it and update the PR accordingly.

**Comment by osorensen** [comment]
This could save us.. https://github.com/RcppCore/RcppArmadillo/blob/master/inst/include/RcppArmadilloExtensions/sample.h

**Comment by osorensen** [comment]
and this https://gallery.rcpp.org/articles/using-the-Rcpp-based-sample-implementation/

**Comment by wleoncio** [comment]
> This could save us.. https://github.com/RcppCore/RcppArmadillo/blob/master/inst/include/RcppArmadilloExtensions/sample.h

I've had problems using that function on multiple cpp files, basically the same as reported [on this Stackoverflow question](https://stackoverflow.com/q/44060134/1169233), but maybe you can make it work. :)

**Comment by wleoncio** [comment]
> The results of some of the tests seem to be platform dependent. I'll look into it and update the PR accordingly.

Funny how usually the macOS checks are the only ones failing, and now it's the only OS passing 😆

**Comment by osorensen** [comment]
> 

Interesting! That is exactly the error message I'm getting. But seems like they have a solution.

Learning a lot from this :-)

**Comment by osorensen** [comment]
That worked :-)

**Comment by osorensen** [comment]
@wleoncio, if these tests pass on all platforms, I think this one can be merged, but please take a critical look. I was able to get rid of all of our custom sampling functions by using `Rcpp::RcppArmadillo::sample()` as defined here and then including the header `sample.h` defined as in the code next below:

https://github.com/ocbe-uio/BayesMallows/blob/2a152d3df5bec752147b3795677417ed9d00d473/src/sample.cpp#L1-L15

https://github.com/ocbe-uio/BayesMallows/blob/2a152d3df5bec752147b3795677417ed9d00d473/src/sample.h#L1-L9

Because we now use this sampler consistently, the expectations for certain random number seeds have changed, and so also the test files.

**Comment by osorensen** [comment]
Just remembered that we painfully learned last autumn that Rcpp::setdiff us platform dependent. It might well be that some of the changes I made here would be unnecessary if we just sort the output. I'll give it a try and come back.

**Comment by osorensen** [comment]
Well, I think this one is ready now. There are some changes in the unit tests, due to different sampling functions. This is mainly for the clustering part of the "old" BayesMallows code.

Wherever a simple `arma::shuffle()` is possible, I have used this. Everywhere else I have used `Rcpp::RcppArmadilloExtensions::sample()`.

**Review by wleoncio — APPROVED** [review]
I'm very impressed! I think you might be having the most productive diaper-changing breaks in the history of humankind. 😆

**Comment by osorensen** [comment]
> I'm very impressed! I think you might be having the most productive diaper-changing breaks in the history of humankind. 😆

I get easily obsessed :-P

**Pull request merged**
