### PR TITLE
Renamed 1 function + 2 test files

### PR DESCRIPTION
**Pull request by wleoncio**
No code changes, only file renaming to match the package standard.

Side effects: unit tests are now in alphabetical order; package is now more OCD-friendly.

### CODE REVIEW

**Review by osorensen — APPROVED** [review]
Great, thanks!

**Comment by osorensen** [comment]
The package test on Travis fails with the following message:

```
ERROR: dependency ‘Rmpfr’ is not available for package ‘CVXR’
* removing ‘/home/travis/R/Library/CVXR’
ERROR: dependency ‘CVXR’ is not available for package ‘PlackettLuce’
* removing ‘/home/travis/R/Library/PlackettLuce’
The downloaded source packages are in
	‘/tmp/RtmpYO4R8o/downloaded_packages’
Warning messages:
1: In i.p(...) : installation of package ‘Rmpfr’ had non-zero exit status
2: In i.p(...) : installation of package ‘CVXR’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘PlackettLuce’ had non-zero exit status
missing: Rmpfr, CVXR, PlackettLuce
The command "Rscript -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
```

I assume this is just a Travis thing, because all these packages seem to have no particular errors on CRAN, and it definitely has nothing to do with the little change you made, so I'll merge anyway.

**Comment by wleoncio** [comment]
Maybe I'm missing something, but I don't think this was merged, only closed, so I'll reopen. Then I'll rerun Travis to give it a second chance on the check.

**Comment by osorensen** [comment]
Thanks! I meant merge, but pressed "close". To early in the morning :-P

**Pull request merged**
